<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>The throw statement is used to create a custom error.
         When an exception is thrown using throw, the catch block will handle it.</h2>
         <!-- throw new Error('Custom error message'); basic syntax -->

    <script>

            function validateNumber(num) {
            if (typeof num !== 'number') {
                throw new TypeError('The argument must be a number');
            }
            return num;
            }

            try {
            validateNumber('string');
            } catch (error) {
            console.error('Caught an error:', error.message);
            }

    </script>
</body>
</html>